source/Refitting/include/DDCellsAutomatonMV.h
This fixes the problem with 
```
DDCellsAutomatonMV.h:134:104: error: 'lcio::ILDCellID0' has not been declared
```
this is defined in `UTIL/ILDConf.h`
=> lcio::ILDCellID0 is inside this include we need this

source/Digitisers/src/DDPlanarDigiProcessor.cc, source/Digitisers/src/DDSpacePointBuilder.cc, source/Digitisers/src/PlanarDigiProcessor.cc, source/Digitisers/src/SimpleCylinderDigiProcessor.cc, source/Digitisers/src/SimpleDiscDigiProcessor.cc, source/Digitisers/src/SimplePlanarDigiProcessor.cc, source/Digitisers/src/SpacePointBuilder.cc, source/Refitting/src/CellsAutomatonMV.cc, source/Refitting/src/DDCellsAutomatonMV.cc, source/Refitting/src/ExtrToSIT.cc, source/Refitting/src/ExtrToTracker.cc, source/Refitting/src/FPCCDFullLDCTracking_MarlinTrk.cc, source/Refitting/src/FPCCDSiliconTracking_MarlinTrk.cc, source/Refitting/src/FullLDCTracking_MarlinTrk.cc, source/Refitting/src/GetPurity.h, source/Refitting/src/RefitProcessor.cc, source/Refitting/src/SiliconTracking_MarlinTrk.cc, source/Refitting/src/TrackSubsetProcessor.cc, source/Refitting/src/TruthTrackFinder.cc, source/Refitting/src/TruthTracker.cc, source/Utils/src/CalcTrackerHitResiduals.cc, source/Utils/src/SetTrackerHitExtensions.cc, source/Utils/src/SplitCollectionByLayer.cc, source/ftf/src/Track.cc, source/ftf/src/TrackFinderFTF.cc, source/ftf/src/TrackFindingParameters.cc
Still a few warnings:
* One warning, which might point to a bug: https://github.com/iLCSoft/MarlinTrkProcessors/commit/0307de590d565ae6e8e1abb9480357924871489c
* use of auto_ptr
* this might also be a bug: https://github.com/iLCSoft/MarlinTrkProcessors/commit/2987b2d672830e857945e94b05b5d2e6c7518af8
* effc++ is off
- Fix many warnings for gcc
- ExtrToSIT::SelectBestCandidateLimited: remove variable shadowing pointer parameter
- ExtrToTracker: Fix bug when using performFinalRefit where the refitted track was not used after refit
=> Fix warnings

source/Refitting/src/TruthTrackFinder.cc
For tracks going in -z direction the sorting by signed Z causes inversion of track direction leading to wrong charge and momentum direction. Thus sort hits by absolute Z.
- TruthTrackFinder::sort_by_z: sort by absolute z. Fixes an issue with wrongly assigned charge and angle for tracks in the backward direction if the fit with hits sorted by radius failed.
=> TruthTrackFinder::sort_by_z: sort by absolute z

source/Refitting/include/TruthTrackFinder.h, source/Refitting/src/TruthTrackFinder.cc
* TruthTrackFinder: hits in the same layer of the same subdetectors are now filtered. Those with higher radius are removed, then the fit is performed. In case the fit fails, those with higher z are removed and a new fit attempt is made.
=> Removing hits from the same layer

source/Refitting/src/TruthTrackFinder.cc
TruthTrackFinder: drop use of gear nullptr accidentally re-introduced in #13
=> TruthTrackFinder: drop use of gear nullptr

.gitignore, source/Digitisers/include/DDTPCDigiProcessor.h, source/Digitisers/src/DDTPCDigiProcessor.cc, source/Digitisers/src/TPCModularEndplate.cc, source/Digitisers/src/TPCModularEndplate.h
- remove hits that are in module gaps on the TPC endplate in DDTPCDigiProcessor
- use the following parameters to define the endplate:
- TPCEndPlateModuleNumbers
- TPCEndPlateModulePhi0s
- TPCEndPlateModuleGapPhi
=> Tpc padplane

source/Digitisers/src/DDPlanarDigiProcessor.cc, source/Refitting/include/RefitFinal.h, source/Refitting/src/RefitFinal.cc
- RefitFinal: new processor for refitting track collections. Does not re-sort hits (like RefitProcessor), different way to setup the initial trackstate for the fit, and different MarlinTrkUtil function being called
- DDPlanarDigi: add absolute values of u and v smearing histograms
=> Add additional Refit Processor

source/Digitisers/src/DDTPCDigiProcessor.cc
- fix DDTPCDigiProcessor
- ensure hits are not smeared beyond cathode
=> ensure hits are not smeared beyond cathode

source/Refitting/src/DDCellsAutomatonMV.cc, source/Refitting/src/ExtrToSIT.cc, source/Refitting/src/ExtrToTracker.cc, source/Refitting/src/FPCCDFullLDCTracking_MarlinTrk.cc, source/Refitting/src/FPCCDSiliconTracking_MarlinTrk.cc, source/Refitting/src/FullLDCTracking_MarlinTrk.cc, source/Refitting/src/RefitFinal.cc, source/Refitting/src/RefitProcessor.cc, source/Refitting/src/SiliconTracking_MarlinTrk.cc, source/Refitting/src/TrackSubsetProcessor.cc, source/Refitting/src/TruthTrackFinder.cc, source/Refitting/src/TruthTracker.cc
- set correct MarlinTrkSystem configuration for every event with `MarlinTrk::TrkSysConfig`
in all tracking processors
needs: iLCSoft/MarlinTrk#7
=> configure MarlinTrkSystem per event in all processors

source/Digitisers/src/DDTPCDigiProcessor.cc, source/Refitting/src/ExtrToSIT.cc
- fix DDTPCDigiProcessor
- allow smearing beyond cathode boundaries
- reduce verbosity in ExtrToSIT
=> Fix tpc cathode

source/Digitisers/include/DDSpacePointBuilder.h, source/Digitisers/src/DDSpacePointBuilder.cc, source/Digitisers/src/DDTPCDigiProcessor.cc, source/Refitting/src/DDCellsAutomatonMV.cc
needed for AIDASoft/DD4hep#345
- Fix for the removal of DDSurfaces which have been merged into DDRec 
-  includes from `DDSurfaces` -> `DDRec`
- namespace `DDSurfaces` -> `dd4hep::rec`
=> Adopt for cleaning of DD4hep

source/Refitting/include/ClonesAndSplitTracksFinder.h, source/Refitting/src/ClonesAndSplitTracksFinder.cc
- ClonesAndSplitTracksFinder: added mergeSplitTracks parameter, that allows one to decide whether to run only the clones skimming or also the merging of split tracks
- mergeSplitTracks = false by default
- mergeSplitTracks = true would enable the treatment of split tracks, which is still work in progress
=> ClonesAndSplitTracksFinder: added option to run clones skimming only

source/Refitting/src/ClonesAndSplitTracksFinder.cc
- ClonesAndSplitTracksFinder: the check for toBeMerged was in the wrong place. Fixed.
=> ClonesAndSplitTracksFinder: fixed toBeMerged condition for split tracks

source/Digitisers/src/DDTPCDigiProcessor.cc
- fixed DDTPCDigiProcessor
- fix B-field correction for the r-phi resolution
- now use (4./B)^2 rather than 4./B
=> fix B-field correction for the r-phi resolution

source/Refitting/src/RefitProcessor.cc
- fix RefitProcessor:
- do not drop tracks in RefitProcessor, even if the refit failed
- ensures that the output collection has the same number of entries
in the same order as the input collection
- needed to identify and compare refitted tracks
=> do not drop tracks in RefitProcessor

source/Refitting/src/RefitFinal.cc
- In case finaliseLCIOTrack fails in the RefitFinal, the track should not be saved
=> Skipping track if finaliseLCIOTrack fails

source/Refitting/include/ClonesAndSplitTracksFinder.h, source/Refitting/include/TruthTrackFinder.h, source/Refitting/src/ClonesAndSplitTracksFinder.cc, source/Refitting/src/TruthTrackFinder.cc, source/Utils/include/HitsSorterAndDebugger.h
- ClonesAndSplitTracksFinder 
- If mergeSplitTracks set to `true`, pairs of tracks above a minimum pT requirements are compared in terms of pt, theta and phi
- For each pair of reconstructed tracks: calculate significance for each parameter, impose a cut on the significance for each parameter, remove possible common hits and sort them in r, fit the new merged track
- Results show positive effect on both single muons and complex events, with no significant increase of the run time ([Link to the slides](https://indico.cern.ch/event/920887/))
=> Merging duplicate tracks

source/Digitisers/src/DDPlanarDigiProcessor.cc
When trying to convert LCIO collections generated by `DDPlanarDigiProcessor`, LCRelationImpl won't generate the "from" and "to" parameters for TrackerHitPlane and SimTrackerHit relation.
- DDPlanarDigiProcessor:  Add setting of the fromType and toType parameters for the LCRelation collection between TrackerHit and SimTrackerHit
=> Use LCRelationNavigator to get "from" and "to" parameters

source/Digitisers/include/DDPlanarDigiProcessor.h, source/Digitisers/src/DDPlanarDigiProcessor.cc
Rebased branch of https://github.com/iLCSoft/MarlinTrkProcessors/pull/48 to fix conflicts
- Added time smearing to the DDPlanarDigiProcessor 
- Introduced a time window for digitized hits in the DDPlanarDigiProcessor 
- Introduced TOF compensation for digitized hits in the DDPlanarDigiProcessor 
=>  Add option for time smearing and TOF compensation in DDPlanarDigiProcessor

source/Digitisers/src/DDPlanarDigiProcessor.cc, source/Digitisers/src/DDSpacePointBuilder.cc
- Center of the SET strips is now properly in the middle of the sensor modules.
- Removed unused `vertex_x`, `vertex_y`, `vertex_z` steering parameters.
This is the fix for the #50 and small optimization mentioned here #54.
Everything is carefully wrapped into `if (_subDetName == "SET")` to not affect reconstruction of the VXD/SIT/FTD hits until further investigation if those are affected and any corrections are needed.
Current change would be impossible for the FTD because FTD strips are perpendicular to the `z` which would give infinity in division by `v[2]`. So even if correction is needed there, then the math would be different.
Not sure what happens inside VXD or SIT...
TODO
=> Fix position of the digitized SET strip hits in the SET

source/Refitting/include/SiliconTracking_MarlinTrk.h
- Make sure that the `_histos` pointer is at least initialized to a `nullptr` to avoid a spurious seg fault when trying to delete it uninitialized.
=> Intialize potentially unused pointer to avoid seg faults

.github/workflows/linux.yml
- Remove the obsolote gcc8 based workflow and update github actions to the latest versions
Fixes #63
=> Remove obsolote gcc8 workflow, update gh actions

source/Digitisers/include/DDTPCDigiProcessor.h, source/Digitisers/src/DDSpacePointBuilder.cc, source/Digitisers/src/DDTPCDigiProcessor.cc, source/Refitting/include/RefitProcessor.h, source/Refitting/src/RefitProcessor.cc
- Use the `LCRelationNavigator` to create output relation collections with the necessary type information.
- This is necessary for automatic conversion from LCIO to EDM4hep when used within the MarlinWrapper and Gaudi. 
=> Make sure to set the necessary type information in relation collections that are created

.github/workflows/key4hep.yml, source/Digitisers/include/DDPlanarDigiProcessor.h, source/Digitisers/include/DDSpacePointBuilder.h, source/Digitisers/include/DDTPCDigiProcessor.h, source/Digitisers/src/FixedPadSizeDiskLayout.cc, source/Digitisers/src/TPCModularEndplate.h, source/Refitting/include/ClonesAndSplitTracksFinder.h, source/Refitting/include/DDCellsAutomatonMV.h, source/Refitting/include/ExtrToSIT.h, source/Refitting/include/ExtrToTracker.h, source/Refitting/include/FPCCDFullLDCTracking_MarlinTrk.h, source/Refitting/include/FPCCDSiliconTracking_MarlinTrk.h, source/Refitting/include/FullLDCTracking_MarlinTrk.h, source/Refitting/include/RefitProcessor.h, source/Refitting/include/SiliconTracking_MarlinTrk.h, source/Refitting/include/TrackSubsetProcessor.h, source/Refitting/include/TruthTrackFinder.h, source/Refitting/include/TruthTracker.h, source/Refitting/src/DDCellsAutomatonMV.cc, source/Refitting/src/SiliconTracking_MarlinTrk.cc, source/Utils/include/CalcTrackerHitResiduals.h, source/Utils/include/SetTrackerHitExtensions.h, source/Utils/include/SplitCollectionByLayer.h
- Fix warnings to make Key4hep based CI workflows pass again
- Remove CentOS7 from Key4hep based workflows since it is no longer supported
=> Fix warnings and remove CentOS7 from CI workflows

source/Refitting/include/FullLDCTracking_MarlinTrk.h, source/Refitting/src/FullLDCTracking_MarlinTrk.cc, source/Refitting/src/SiliconTracking_MarlinTrk.cc
- Remove the hardcoded (ILD) detector names from the FullLDC tracking to allow its usage with the `v11` model of ILD.
- Keep defaults compatible with the non-hybrid ILD models
=> Make FullLDC tracking more flexible

source/Refitting/src/ClonesAndSplitTracksFinder.cc
when mergeSplitTracks is false. See https://github.com/key4hep/CLDConfig/issues/69. I ran the CLD reconstruction with this change and I can see the subdetector hit numbers have the same values as in the original track.
- Set the subdetectorHitNumbers in ClonesAndSplitTracksFinder that was not being set (defaulted to 0) when `mergeSplitTracks` is false.
=> Set the subdetectorHitNumbers in ClonesAndSplitTracksFinder
